name: Build docker build environments

on:
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:

    runs-on: ubuntu-20.04

    strategy:
        matrix:
          tag: [mipsel, octeon]
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/ubnt-build:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Build toolchain environment
        run: cd ci/${{ matrix.tag }} && docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: docker push "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"