name: Build docker build environments

on:
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:

    runs-on: ubuntu-20.04

    strategy:
        matrix:
          tag: [mipsel, octeon]
          type: [kernel]
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/ubnt-build:${{ matrix.tag }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v2

      - name: Build kernel environment
        if: ${{ matrix.type == 'kernel' }}
        run: docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" -f ci/${{ matrix.tag }}/Dockerfile .

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: docker push "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"